# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Greenlight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Greenlight
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'

  target 'GreenlightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GreenlightUITests' do
    # Pods for testing
  end

end
